config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :home, only: [:index, :landing]
   root 'home#landing'
  resources :posts, only: [:new, :create, :show]

  namespace :adminpanel do
    root 'users#index', as: :root
    resources :categories, only: [:new, :create, :index]
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  validates :title, presence: true, length: { in: 2..66 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_attached_file :foto, styles: { large: "1280x1024>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing/missing.png"
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\z/
  validates :title, presence: true, length: { in: 2..30 }
  validates :description, presence: true, length: { minimum: 3 }, allow_blank: true
  validates :price, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/adminpanel/administrative_controller.rb
module Adminpanel
  class AdministrativeController < ApplicationController
    layout 'adminpanel'
    before_action :redirect_if_not_admin

    def redirect_if_not_admin
      redirect_to new_admin_session_path unless admin_signed_in?
    end

    def current_user
      current_admin
    end
  end
end

app/controllers/adminpanel/categories_controller.rb
module Adminpanel
class CategoriesController < AdministrativeController

  def index
    @category = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path
      flash[:notice] = 'Категорія створена.'
    else
      render :new,
             alert: 'Категорію нестворено.'
    end
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

end
end

app/controllers/adminpanel/users_controller.rb
module Adminpanel
  class UsersController < AdministrativeController
    def index
      @users = User.all
    end
  end
end

app/controllers/admins/passwords_controller.rb
class Admins::PasswordsController < Devise::PasswordsController
  layout false

  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  layout false

  # GET /resource/sign_in
  def new
    super
  end

# POST /resource/sign_in
# def create
#   super
# end

# DELETE /resource/sign_out
# def destroy
#   super
# end

# protected

# If you have extra params to permit, append them to the sanitizer.
# def configure_sign_in_params
#   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path
      flash[:notice] = 'Категорія створена.'
    else
      render :new,
             alert: 'Категорію нестворено.'
    end
  end

  private

  def category_params
    params.require(:category).permit(:title)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @posts = Post.page(params[:page]).per(6)
  end

  def landing
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, except: [:new, :create]

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
      flash[:notice] = 'Пост створено.'
    else
      render :new,
      alert: 'Пост нестворено.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :foto, :category_id, :price).merge(user_id: current_user.id)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/adminpanel/categories/index.html.erb
<%=link_to 'Створити категорію', new_adminpanel_category_path %></br>

<% @category.each do |category| %>
    <%= category.title %></br>
<% end %>

app/views/adminpanel/categories/new.html.erb
<%if admin_signed_in?%>
    <div class="container">
      <h1>Створити категорію!</h1>
      <%= simple_form_for(@category,url: {action: :create}, class: 'form-horizontal') do |f|%>
          <div class="row">
            <div class=" col-lg-offset-1 col-lg-9  col-md-10 ">
              <div class="form-group">
                <%= f.input :title%>
              </div>
            </div>
          </div>
          <div class="button-display-flex">
            <%= f.button :submit, id: 'category-submit-center' %>
          </div>
      <% end %>
    </div>
<% end %>

app/views/adminpanel/users/index.html.erb
ergreg

app/views/categories/new.html.erb
<%if user_signed_in?%>
    <div class="container">
      <h1>Створити категорію!</h1>
      <%= simple_form_for(@category,url: {action: :create}, class: 'form-horizontal') do |f|%>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.input :title %>
              </div>
            </div>
          </div>
          <div class="col">
            <%= f.button :submit %>
          </div>
      <% end %>
    </div>
<% end %>

app/views/home/index.html.erb
<div class="container">
<%= content_tag :h2, 'Пости відсутні' unless @posts.any? %>
<h1 id="heading-home-text">Catalog</h1>
<div class="row">
  <% @posts.each do |post| %>
      <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div>
          <div class="frame">
            <%= image_tag post.foto, id:'home-index-post-foto' %>
          </div>
          <div id="home-list-block-name">
            <%= post.title %>
          </div>
          <div id="home-list-block-description">
            <%= post.description %>
          </div>
          <div id="home-list-block-price">
            <%= post.price %>
          </div>
          <div class="btn btn-info" id="post-show">
            <%= link_to 'Детальніше', post %>
          </div>
        </div>

      </div>
  <% end %>
  <%= paginate @posts %>
</div>
</div>

app/views/home/landing.html.erb
<%= render partial: 'partials/header' %>
<div class="first-block">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-content first-block-content">
        <p>Buy the best!</p>
        <h1>TRY TO SHOP ONLINE STORE, ALONG WITH KOLYA</h1>
        <p id="p_first"> BUY WITH MY SHOP, AND BE BETTER</p>
        <button class="btn"><%= link_to 'JOIN US', '#' %> </button>
      </div>
    </div>
  </div>
</div>
<section class="section-color-grey section-padding">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-xs-6">
        <%=image_tag 'shopworker.jpg', class: 'image-responsive' %>
      </div>
      <div class="col-sm-6 col-xs-6">
        <h3 class="about-us-header">ABOUT US</h3>
        <p class="blue-content">
          Our aim is to make mainstream and luxury fragrance affordable and accessible to all. We showcase over 130 fragrance brands, all of which are available for you to browse online at your leisure. Don't forget our fabulous selections in-store too!
        </p>
        <p>
          We pride ourselves in delivering outstanding service to our customers, we have recently been awarded for excellent customer service. Whether you choose to shop in one of over 183 stores, online or over the phone our friendly team are on hand to help make finding the perfect fragrance a pleasurable experience for all.
        </p>
        <p class="read-more">
          <%=link_to 'Read More', '#' %>
        </p>
      </div>
    </div>
  </div>
</section>
<section class="section-padding">
  <div class="container">
    <div class="text-content header-block">
      <h2>APP FEATURES</h2>
      <%=image_tag 'line.png' %>
      <p>You will receive an email confirming your credit card payment, or if you wish to pay by EFT you will receive a confirmation email with instructions and order number for making a Bank Transfer.</p>
    </div>
    <div class="row">
      <div class="col-sm-6 col-xs-6">
        <%=image_tag 'bags.jpg' %>
        <h3>GOOD SHOP</h3>
        <p>Best Buy Co., Inc. is a U.S transnational consumer electronics corporation headquartered in Richfield, Minnesota, a Minneapolis suburb. Internationally, it also operates in Canada and Mexico. It was formerly operational in China until February 2011 (when the faction was merged with Five Star) and in Europe until 2012.[3] The company was founded by Richard M. Schulze and Gary Smoliak in 1966 as an audio specialty store. In 1983, it was renamed and rebranded with more emphasis placed on consumer electronics.</p>
        <p class="read-more">
          <%=link_to 'Read More', '#' %>
        </p>
      </div>
      <div class="col-sm-6 col-xs-6">
        <%=image_tag 'basket.png' %>
        <h3>MANY SHOPPER</h3>
        <p>Best Buy Co., Inc. is a U.S transnational consumer electronics corporation headquartered in Richfield, Minnesota, a Minneapolis suburb. Internationally, it also operates in Canada and Mexico. It was formerly operational in China until February 2011 (when the faction was merged with Five Star) and in Europe until 2012.[3] The company was founded by Richard M. Schulze and Gary Smoliak in 1966 as an audio specialty store. In 1983, it was renamed and rebranded with more emphasis placed on consumer electronics.</p>
        <p class="read-more">
          <%=link_to 'Read More', '#' %>
        </p>
      </div>
    </div>
  </div>
</section>
<section class="section-color-grey section-padding">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-xs-6 col-sm-push-6 col-xs-push-6">
        <%=image_tag 'car.jpg' %>
      </div>
      <div class="col-sm-6 col-xs-6 col-sm-pull-6 col-xs-pull-6">
        <h3>OUR WORK</h3>
        <p class="blue-content">In 2000, Best Buy formed Redline Entertainment, an independent music label and action-sports video distributor. The company acquired Magnolia Hi-Fi, Inc., an audio-video retailer located in California</p>
        <p>Best Buy partnered with Roxio's CinemaNow to launch an on-demand movie download service that would allow customers to stream content to any device sold by Best Buy that connected to the Internet in November 2009. In December, the first Turkish Best Buy opened in İzmir.</p>
        <p class="read-more">
          <%=link_to 'Read More', '#' %>
        </p>
      </div>
    </div>
  </div>
</section>
<section>
  <div class="container">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-3 text-content">
        <%=image_tag 'shop-litle.png' %>
        <h3>SHOP START</h3>
        <p>A retailer or a shop is a business that presents a selection of goods and offers to trade</p>
        <p class="read-more">
          <%=link_to 'Read More', '#' %>
        </p>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-3 text-content">
        <%=image_tag 'basket-litle.jpg' %>
        <h3>BASKET ON</h3>
        <p>In modern days customer focus is more transferred towards online shopping</p>
        <p class="read-more">
          <%=link_to 'Read More', '#' %>
        </p>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-3 text-content">
        <%=image_tag 'delivery-litle.jpeg' %>
        <h3>DELIVERY</h3>
        <p>The shopping experience can also be influenced by other shoppers.</p>
        <p class="read-more">
          <%=link_to 'Read More', '#' %>
        </p>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-3 text-content">
        <%=image_tag 'final-litle.jpg' %>
        <h3>YOU HAPPY</h3>
        <p>You always be happy when you buy in my shop</p>
        <p class="read-more">
          <%=link_to 'Read More', '#' %>
        </p>
      </div>
    </div>
  </div>
</section>
<section class="blue-section">
  <div class="container-fluid no_padding">
    <div class="row row-margin-zero">
      <div class="features-image col-sm-6 col-xs-6 no_padding"></div>
      <div class="col-sm-6 col-xs-6 text-content-white">
        <div class="header-block-white">
          <h2>ONLINE SHOP FEATURES</h2>
          <%=image_tag 'white-line.png' %>
        </div>
        <div class="features-content">
          <div class="row features-margin">
            <div class="col-sm-2 col-xs-3">
              <%=image_tag 'cart-xs.png' %>
            </div>
            <div class="col-sm-10 col-xs-9">
              <h4>TAKE CART</h4>
              <p>You can take just cart and go shopper</p>
            </div>
          </div>
          <div class="row features-margin">
            <div class="col-sm-2 col-xs-3">
              <%=image_tag 'heart-xs.png' %>
            </div>
            <div class="col-sm-10 col-xs-9">
              <h4>ON HEART</h4>
              <p>"Love in Store" is a song by British-American rock group Fleetwood Mac</p>
            </div>
          </div>
          <div class="row features-margin">
            <div class="col-sm-2 col-xs-3">
              <%=image_tag 'money-xs.jpg' %>
            </div>
            <div class="col-sm-10 col-xs-9">
              <h4>PAY MONEY</h4>
              <p>Early in life, Kei started writing lyrics as a way to cope with his depression and dark feelings.</p>
            </div>
          </div>
          <div class="row features-margin">
            <div class="col-sm-2 col-xs-3">
              <%=image_tag 'bag-xs.png' %>
            </div>
            <div class="col-sm-10 col-xs-9">
              <h4>PUT IN THE BAG</h4>
              <p>Tourists have departed Brownstone National Park where Humphrey lives, leaving trash everywhere.</p>
            </div>
          </div>
          <div class="row features-margin">
            <div class="col-sm-2 col-xs-3">
              <%=image_tag 'thankyou-xs.png' %>
            </div>
            <div class="col-sm-10 col-xs-9">
              <h4>THANK YOU</h4>
              <p>"Thank you" is a common expression of gratitude.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="grey-section">
  <div class="container-fluid no_padding">
    <div class="row features-margin">
      <div class="col-sm-6 no_padding cp-image col-sm-push-6"></div>
      <div class="col-sm-6 cp-picked col-sm-pull-6">
        <h3>MULTIPLATFORM APP</h3>
        <p>Platform can refer to the type of processor(CPU) or other hardware on which a given operating system or application runs, the type of operating system on a computer or the combination of the type of hardware and the type of operating system running on it. An example of a common platform is Microsoft Windows running on the x86 architecture. Other well-known desktop computer platforms include Linux/Unix and macOS - both of which are themselves cross-platform.</p>
        <p class="p-padding-20">There are, however, many devices such as smartphones that are also effectively computer platforms but less commonly thought about in that way. Application software can be written to depend on the features of a particular platform—either the hardware, operating system, or virtual machine it runs on. The Java platform is a virtual machine platform which runs on many operating systems and hardware types, and is a common platform for software to be written for.</p>
        <h3>USE BETTER FOR SHOPPER</h3>
        <p>Web applications are typically described as cross-platform because, ideally, they are accessible from any of various web browsers within different operating systems.</p>
        <p class="read-more">
          <%=link_to 'Read More', '#' %>
        </p>
      </div>
    </div>
  </div>
</section>

<%= render partial: 'partials/footer' %>

app/views/layouts/adminpanel.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Shop | Admin</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
  <%= stylesheet_link_tag    'adminlte.min' %>
  <%= stylesheet_link_tag    'skin-green.min' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' =>'reload' %>
  <!-- Ionicons -->
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css"> -->
  <!-- Theme style -->
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect.
  -->

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-green sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>Shop</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">Shop</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li>
          <li>
            <%= link_to destroy_admin_session_path, method: "delete" do %>
                <i class="fa fa-sign-out"></i>
                <span><%=t'exit'%></span>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- search form (Optional) -->
      <!--       <form action="#" method="get" class="sidebar-form">
              <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                      <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                      </button>
                    </span>
              </div>
            </form> -->
      <!-- /.search form -->

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <!-- Optionally, you can add icons to the links -->
        <li><a href="<%= adminpanel_root_path %>"><i class="fa fa-users"></i><span>Користувачі</span></a></li>
        <li><a href="<%= adminpanel_categories_path %>"><i class="fa fa-list"></i><span>Категорії</span></a></li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <%= render  'partials/notification' %>
      <!-- Your Page Content Here -->
      <%= yield %>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- AdminLTE App -->
<%= javascript_include_tag 'adminlte.min' %>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. Slimscroll is required when using the
     fixed layout. -->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catalog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="body-font">

      <%= render partial: 'partials/notification' %>
<%= yield %>
    </div>
</body>
</html>

app/views/partials/_footer.html.erb
<footer class="footer-padding">
  <div class="container">
    <div class="row text-content">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
        <ul class="inline-social">
          <li class="list-style-type">
            <%=link_to '#', class:'text-decoration-none' do %>
                <i class="fa fa-facebook facebook-color icon-circle-sm icon-blue icon-2x"></i>
            <% end %>
          </li>
          <li class="list-style-type">
            <%=link_to '#', class:'text-decoration-none' do %>
                <i class="fa fa-twitter facebook-color icon-circle-sm icon-blue icon-2x"></i>
            <% end %>
          </li>
          <li class="list-style-type">
            <%=link_to '#', class:'text-decoration-none' do %>
                <i class="fa fa-google-plus facebook-color icon-circle-sm icon-blue icon-2x"></i>
            <% end %>
          </li>
          <li class="list-style-type">
            <%=link_to '#', class:'text-decoration-none' do %>
                <i class="fa fa-instagram facebook-color icon-circle-sm icon-blue icon-2x"></i>
            <% end %>
          </li>
          <li class="list-style-type">
            <%=link_to '#', class:'text-decoration-none' do %>
                <i class="fa fa-linkedin facebook-color icon-circle-sm icon-blue icon-2x"></i>
            <% end %>
          </li>
        </ul>
        <div class="line-separate"></div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <div class="line-separate"></div>
        <div>
          <p>2017 © create by Kolya Makogin</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/partials/_header.html.erb
<header class="clearfix">
  <nav id="header-nav" class="menu-bar navbar navbar-default navbar-fixed-top clearfix" >
    <div class="container">
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="logo-image">
          <%= link_to root_path do  %>
              <%= image_tag ('shop.jpg') %>
          <% end %>
        </div>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="hidden">
          <li class="menu active landing-link-color"><%=link_to "Home", home_index_path, class: 'landing-link-color' %></li>
          </li>
          <li class="page-scroll">
          <li class="menu active"><%=link_to "Home", home_index_path, class: 'page landing-link-color' %></li>
          </li>
          <li class="page-scroll">
          <li class="menu active"><%=link_to "Home", home_index_path, class: 'page landing-link-color' %></li>
          </li>
          <li class="page-scroll">
          <li class="menu active"><%=link_to "Home", home_index_path, class: 'page landing-link-color' %></li>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/partials/_notification.html.erb
<% if notice %>
<script type="text/javascript" charset="utf-8">
    $.gritter.add({
        // heading of the notification
        title: 'Повідомлення',
        // the text inside the notification
        text: '<%= notice %>',
        time: 300000,
        image: '<%= image_path "Bang_white.svg" %>'
    });
    <% end %>
</script>
<% if alert %>
<script type="text/javascript" charset="utf-8">
    $.gritter.add({
        // heading of the notification
        title: 'Увага!',
        // the text inside the notification
        text: '<%= alert %>',
        time: 3000,
        image: '<%= image_path "Bang_red.svg" %>'
    });

    <% end %>



</script>
<script>
    $('.gritter-image').addClass('bang');
</script>

app/views/posts/new.html.erb
<%if user_signed_in?%>
    <div class="container">
      <h1>Створити пост!</h1>
      <%= simple_form_for(@post,url: {action: :create}, class: 'form-horizontal') do |f|%>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= f.input :title %>
                <%= f.input :description %>
                <%= f.input :price %>
                <%= f.input :foto, as: :file %>
                <%= f.collection_select :category_id, Category.all, :id, :title %>
              </div>
            </div>
          </div>
          <div class="col">
            <%= f.button :submit %>
          </div>
      <% end %>
    </div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
<div class="row">
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 container-show">
    <div class="show-frame">
      <%= image_tag @post.foto.url, class: "images-small-circle-size" %>
    </div>
  </div>

  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 container-show">
    <div>
      <h1><%= @post.title %></h1>
    </div>
    <div>
      <p><%= @post.description %></p>
    </div>
  </div>
</div>
    </div>